from __future__ import annotations

import json
import os
import sys
import subprocess
from pathlib import Path

from google import genai
from google.genai import types


ROOT = Path(__file__).resolve().parents[1]

API_KEY = os.environ.get("GEMINI_API_KEY")
MODEL = os.environ.get("GEMINI_MODEL", "gemini-3.6-flash")

# ============================================================
# FOUR-LAYER AGENT CONTEXT
# ============================================================

MASTER_DOCUMENT_FILE = (
    ROOT / "docs/PYHOK_MASTER_ARCHITECTURE.md"
)

CONSTITUTION_FILE = (
    ROOT / "prompts/00_agent_constitution.system.txt"
)

CURRENT_KNOWLEDGE_FILE = (
    ROOT / "generator/input/current_knowledge_context.json"
)

EVOLUTION_POLICY_FILE = (
    ROOT / "evolution/evolution-policy.json"
)

# Compatibility/context artifact generated by the repository.
AGENT_CONTEXT_FILE = (
    ROOT / "generator/input/agent_context.json"
)

# Auditor-specific instructions.
AUDITOR_PROMPT_FILE = (
    ROOT / "prompts/01_graph_auditor.system.txt"
)

OUTPUT_FILE = (
    ROOT / "generator/output/audit.json"
)


# ============================================================
# FILE HELPERS
# ============================================================

def read_text(path: Path) -> str:
    if not path.exists():
        raise SystemExit(
            f"Required file not found: {path}"
        )

    return path.read_text(
        encoding="utf-8"
    )


def read_json(path: Path) -> dict:
    if not path.exists():
        raise SystemExit(
            f"Required JSON file not found: {path}"
        )

    try:
        return json.loads(
            path.read_text(
                encoding="utf-8"
            )
        )
    except json.JSONDecodeError as exc:
        raise SystemExit(
            f"Invalid JSON in {path}: {exc}"
        )


# ============================================================
# CONTEXT GENERATION
# ============================================================

def build_context() -> None:
    """
    Always regenerate the repository-derived context before
    auditing.

    The current knowledge context must represent the actual
    repository state at the moment of the audit.
    """

    print("Building current repository context...")

    result = subprocess.run(
        [
            sys.executable,
            str(
                ROOT /
                "generator/build_agent_context.py"
            )
        ],
        cwd=ROOT,
        capture_output=True,
        text=True
    )

    if result.stdout:
        print(result.stdout)

    if result.returncode != 0:
        if result.stderr:
            print(result.stderr)

        raise SystemExit(
            "Failed to build agent context."
        )


# ============================================================
# FOUR-LAYER CONTEXT
# ============================================================

def build_four_layer_context() -> str:
    """
    Assemble the four epistemic layers used by the agent.

    Layer 1:
        Master Document
        Defines what PyHok is and what the architecture means.

    Layer 2:
        Agent Constitution
        Defines how the agent must reason.

    Layer 3:
        Current Knowledge Context
        Defines what actually exists in the repository now.

    Layer 4:
        Evolution Policy
        Defines what the agent is authorized to propose.

    IMPORTANT:
        The Master Document is NOT evidence that an entity exists.
        Only the Current Knowledge Context establishes current
        repository state.
    """

    master_document = read_text(
        MASTER_DOCUMENT_FILE
    )

    constitution = read_text(
        CONSTITUTION_FILE
    )

    current_knowledge = read_json(
        CURRENT_KNOWLEDGE_FILE
    )

    evolution_policy = read_json(
        EVOLUTION_POLICY_FILE
    )

    context = f"""
================================================================
PYHOK KNOWLEDGE AGENT — FOUR-LAYER CONTEXT
================================================================

IMPORTANT EPISTEMIC RULE:

The following four layers have different authorities.

LAYER 1 — MASTER DOCUMENT
Purpose:
Define what PyHok is, its architecture, goals, concepts,
terminology and intended system behavior.

The Master Document explains the TARGET ARCHITECTURE.

It MUST NOT be interpreted as proof that a signal, method,
question, relation, sensor or runtime capability currently exists.

If something is described in the Master Document but absent
from the Current Knowledge Context, it is NOT currently
available to the Knowledge Graph.

---------------------------------------------------------------

LAYER 2 — AGENT CONSTITUTION
Purpose:
Define how the agent must reason, what epistemic discipline
it must follow, and what kinds of reasoning are forbidden.

The Constitution governs the agent's reasoning process.

---------------------------------------------------------------

LAYER 3 — CURRENT KNOWLEDGE CONTEXT
Purpose:
Represent the actual repository state available during this run.

THIS IS THE AUTHORITATIVE SOURCE FOR WHAT CURRENTLY EXISTS.

Only entities explicitly present here may be treated as existing.

Anything absent must be treated as UNKNOWN.

Do not infer existence from the Master Document.

---------------------------------------------------------------

LAYER 4 — EVOLUTION POLICY
Purpose:
Define what the agent is authorized to propose and the limits
that apply to evolution.

The Policy governs authorization.

---------------------------------------------------------------

AUTHORITY ORDER

For architectural meaning:
    Master Document

For reasoning behavior:
    Agent Constitution

For current existence:
    Current Knowledge Context

For authorization:
    Evolution Policy

When these layers appear to conflict, preserve their separation.
Do not silently merge them.

================================================================
LAYER 1 — MASTER DOCUMENT
================================================================

{master_document}

================================================================
LAYER 2 — AGENT CONSTITUTION
================================================================

{constitution}

================================================================
LAYER 3 — CURRENT KNOWLEDGE CONTEXT
================================================================

{json.dumps(
    current_knowledge,
    ensure_ascii=False,
    indent=2
)}

================================================================
LAYER 4 — EVOLUTION POLICY
================================================================

{json.dumps(
    evolution_policy,
    ensure_ascii=False,
    indent=2
)}

================================================================
END FOUR-LAYER CONTEXT
================================================================
"""

    return context


# ============================================================
# AUDIT RESPONSE SCHEMA
# ============================================================

RESPONSE_SCHEMA = {
    "type": "object",
    "required": [
        "status",
        "opportunities"
    ],
    "properties": {
        "status": {
            "type": "string",
            "enum": [
                "ANALYSIS_COMPLETE",
                "NO_USEFUL_CHANGE"
            ]
        },
        "opportunities": {
            "type": "array",
            "maxItems": 3,
            "items": {
                "type": "object",
                "required": [
                    "opportunity_id",
                    "type",
                    "domain",
                    "description",
                    "existing_questions",
                    "available_signals",
                    "available_methods",
                    "estimated_novelty",
                    "estimated_coverage_gain",
                    "priority"
                ],
                "properties": {
                    "opportunity_id": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string",
                        "enum": [
                            "COMPUTABLE_EVOLUTION",
                            "GAP"
                        ]
                    },
                    "domain": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    },
                    "existing_questions": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "available_signals": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "available_methods": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "estimated_novelty": {
                        "type": "number"
                    },
                    "estimated_coverage_gain": {
                        "type": "number"
                    },
                    "priority": {
                        "type": "number"
                    }
                }
            }
        }
    }
}


# ============================================================
# MAIN
# ============================================================

def main() -> None:

    if not API_KEY:
        raise SystemExit(
            "GEMINI_API_KEY is missing."
        )

    # Always rebuild the repository-derived context.
    build_context()

    # Make sure the generated current context exists.
    if not CURRENT_KNOWLEDGE_FILE.exists():
        raise SystemExit(
            "Current knowledge context was not generated."
        )

    auditor_prompt = read_text(
        AUDITOR_PROMPT_FILE
    )

    four_layer_context = (
        build_four_layer_context()
    )

    user_prompt = f"""
You are now performing an epistemic audit of the PyHok
Knowledge Graph.

Your task is NOT to create knowledge.

Your task is to inspect the four-layer context and identify
only defensible opportunities for evolution.

The Master Document tells you what PyHok IS and what the
architecture is intended to accomplish.

The Current Knowledge Context tells you what ACTUALLY EXISTS.

The Agent Constitution tells you HOW TO THINK.

The Evolution Policy tells you WHAT YOU ARE AUTHORIZED TO PROPOSE.

CRITICAL RULE:

Never treat an architectural capability described by the
Master Document as an existing capability unless it is also
present in the Current Knowledge Context.

For example:

If the Master Document describes an eye-tracking signal,
but Current Knowledge contains no eye-tracking signal,
then eye-tracking is UNKNOWN/UNAVAILABLE for the current graph.

You may identify the absence as an architectural gap if the
Constitution and Policy permit identifying such a gap.

You may NOT invent the missing signal.

You may NOT invent a method for evaluating it.

You may NOT invent a QuestionEntity that depends on it.

You may NOT fabricate evidence.

A useful opportunity must therefore be grounded in what the
repository can actually support.

The most important objective is NOT to maximize the number of
opportunities.

The objective is to find opportunities that meaningfully
improve the Knowledge Graph and ultimately help the system
represent observable patterns relevant to PyHok.

A proposal that is technically valid but conceptually trivial,
redundant, unsupported, or disconnected from meaningful
observational reasoning is NOT useful.

Likewise, if the current graph does not contain enough
observable infrastructure to support a defensible evolution,
you must abstain.

Do not generate an opportunity merely because the graph is
small.

Do not generate an opportunity merely because a mission domain
has zero questions.

Do not generate an opportunity merely to make the system
appear to evolve.

At most three opportunities may be returned.

Return JSON only.

================================================================
AUDITOR-SPECIFIC INSTRUCTIONS
================================================================

{auditor_prompt}

================================================================
FOUR-LAYER CONTEXT
================================================================

{four_layer_context}

================================================================
END INPUT
================================================================
"""

    client = genai.Client(
        api_key=API_KEY
    )

    response = client.models.generate_content(
        model=MODEL,
        contents=user_prompt,
        config=types.GenerateContentConfig(
            system_instruction=auditor_prompt,
            response_mime_type="application/json",
            response_schema=RESPONSE_SCHEMA
        )
    )

    if not response.text:
        raise SystemExit(
            "Gemini returned an empty response."
        )

    try:
        result = json.loads(
            response.text
        )
    except json.JSONDecodeError as exc:
        print(response.text)
        raise SystemExit(
            f"Gemini returned invalid JSON: {exc}"
        )

    OUTPUT_FILE.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    OUTPUT_FILE.write_text(
        json.dumps(
            result,
            ensure_ascii=False,
            indent=2
        ) + "\n",
        encoding="utf-8"
    )

    print("=== AUDIT RESULT ===")
    print(
        json.dumps(
            result,
            ensure_ascii=False,
            indent=2
        )
    )


if __name__ == "__main__":
    main()
